general.import = ["~/.config/alacritty/themes/themes/monokai_charcoal.yaml"]

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[window.dimensions]
columns = 80
lines = 25

[window]
option_as_alt = "Both"
