-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-ivo"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { bg = "#e58385", fg = "#33353b" })
hi(0, "@comment.hint", { bg = "#8daaec", fg = "#33353b" })
hi(0, "@comment.note", { bg = "#8daaec", fg = "#33353b" })
hi(0, "@comment.todo", { bg = "#edbfbf", fg = "#33353b" })
hi(0, "@comment.warning", { bg = "#e4c893", fg = "#33353b" })
hi(0, "@comment.warning.gitcommit", { fg = "#e0c99d" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { fg = "#e8a380" })
hi(0, "@constant.java", { fg = "#8dc5bd" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#90bfd5" })
hi(0, "@constructor.lua", { fg = "#e8c1c1" })
hi(0, "@constructor.tsx", { fg = "#bbbcea" })
hi(0, "@constructor.typescript", { fg = "#bbbcea" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { fg = "#bbbcea" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#e8a380" })
hi(0, "@function.builtin.bash", { fg = "#de8889", italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#8dc5bd" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#a5ced6" })
hi(0, "@keyword.function", { fg = "#c6a2de" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#c6a2de" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#c6a2de" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label.json", { fg = "#90abe5" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.interface", { fg = "#e8c1c1" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#c8d0f0" })
hi(0, "@markup.environment", { fg = "#eebce1" })
hi(0, "@markup.environment.name", { fg = "#90abe5" })
hi(0, "@markup.heading", { bold = true, fg = "#90abe5" })
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = "#e29ea0", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.url", { fg = "#eed7d2", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#acce96" })
hi(0, "@markup.list.unchecked", { fg = "#878c9a" })
hi(0, "@markup.math", { fg = "#90abe5" })
hi(0, "@markup.raw", { fg = "#8dc5bd" })
hi(0, "@markup.strikethrough", { fg = "#c8d0f0", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#e29ea0" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = "#bbbcea", italic = true })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#bbbcea", italic = true })
hi(0, "@number.css", { fg = "#e8a380" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#e29ea0" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#bbbcea" })
hi(0, "@property.class.css", { fg = "#e0c99d" })
hi(0, "@property.cpp", { fg = "#c8d0f0" })
hi(0, "@property.css", { fg = "#bbbcea" })
hi(0, "@property.id.css", { fg = "#90abe5" })
hi(0, "@property.toml", { fg = "#90abe5" })
hi(0, "@property.typescript", { fg = "#bbbcea" })
hi(0, "@punctuation.bracket", { fg = "#979db0" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#eebce1" })
hi(0, "@string.plain.css", { fg = "#e8a380" })
hi(0, "@string.regex", { fg = "#e8a380" })
hi(0, "@string.regexp", { fg = "#e8a380" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.symbol", { fg = "#e8c1c1" })
hi(0, "@string.special.symbol.ruby", { fg = "#e8c1c1" })
hi(0, "@string.special.url", { fg = "#eed7d2", italic = true, underline = true })
hi(0, "@symbol", { fg = "#e8c1c1" })
hi(0, "@symbol.ruby", { fg = "#e8c1c1" })
hi(0, "@tag", { fg = "#c6a2de" })
hi(0, "@tag.attribute", { fg = "#8dc5bd", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#8dc5bd", italic = true })
hi(0, "@tag.delimiter", { fg = "#a5ced6" })
hi(0, "@text", { fg = "#c8d0f0" })
hi(0, "@text.danger", { bg = "#e58385", fg = "#33353b" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#e29ea0", italic = true })
hi(0, "@text.environment", { fg = "#eebce1" })
hi(0, "@text.environment.name", { fg = "#90abe5" })
hi(0, "@text.literal", { fg = "#8dc5bd" })
hi(0, "@text.math", { fg = "#90abe5" })
hi(0, "@text.note", { bg = "#8daaec", fg = "#33353b" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = "#c8d0f0", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#e29ea0" })
hi(0, "@text.title", { bold = true, fg = "#90abe5" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#edbfbf", fg = "#33353b" })
hi(0, "@text.todo.checked", { fg = "#acce96" })
hi(0, "@text.todo.unchecked", { fg = "#878c9a" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#e4c893", fg = "#33353b" })
hi(0, "@type.builtin", { fg = "#e0c99d" })
hi(0, "@type.builtin.c", { fg = "#e0c99d" })
hi(0, "@type.builtin.cpp", { fg = "#e0c99d" })
hi(0, "@type.css", { fg = "#bbbcea" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#c6a2de" })
hi(0, "@variable", { fg = "#c8d0f0" })
hi(0, "@variable.builtin", { fg = "#de8889" })
hi(0, "@variable.member", { fg = "#bbbcea" })
hi(0, "@variable.parameter", { fg = "#e29ea0" })
hi(0, "Added", { ctermfg = 10, fg = "#bcf3c6" })
hi(0, "AlphaButtons", { fg = "#bbbcea" })
hi(0, "AlphaFooter", { fg = "#e0c99d", italic = true })
hi(0, "AlphaHeader", { fg = "#90abe5" })
hi(0, "AlphaHeaderLabel", { fg = "#e8a380" })
hi(0, "AlphaShortcut", { fg = "#acce96" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#e8a380" })
hi(0, "Changed", { ctermfg = 14, fg = "#9bf5f4" })
hi(0, "Character", { fg = "#8dc5bd" })
hi(0, "CmpItemAbbr", { fg = "#979db0" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#777a86", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#c8d0f0" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#c8d0f0" })
hi(0, "CmpItemKind", { fg = "#90abe5" })
hi(0, "CmpItemKindClass", { fg = "#e0c99d" })
hi(0, "CmpItemKindColor", { fg = "#de8889" })
hi(0, "CmpItemKindConstant", { fg = "#e8a380" })
hi(0, "CmpItemKindConstructor", { fg = "#90abe5" })
hi(0, "CmpItemKindCopilot", { fg = "#8dc5bd" })
hi(0, "CmpItemKindEnum", { fg = "#acce96" })
hi(0, "CmpItemKindEnumMember", { fg = "#de8889" })
hi(0, "CmpItemKindEvent", { fg = "#90abe5" })
hi(0, "CmpItemKindField", { fg = "#acce96" })
hi(0, "CmpItemKindFile", { fg = "#90abe5" })
hi(0, "CmpItemKindFolder", { fg = "#90abe5" })
hi(0, "CmpItemKindFunction", { fg = "#90abe5" })
hi(0, "CmpItemKindInterface", { fg = "#e0c99d" })
hi(0, "CmpItemKindKeyword", { fg = "#de8889" })
hi(0, "CmpItemKindMethod", { fg = "#90abe5" })
hi(0, "CmpItemKindModule", { fg = "#90abe5" })
hi(0, "CmpItemKindOperator", { fg = "#90abe5" })
hi(0, "CmpItemKindProperty", { fg = "#acce96" })
hi(0, "CmpItemKindReference", { fg = "#de8889" })
hi(0, "CmpItemKindSnippet", { fg = "#c6a2de" })
hi(0, "CmpItemKindStruct", { fg = "#90abe5" })
hi(0, "CmpItemKindText", { fg = "#8dc5bd" })
hi(0, "CmpItemKindTypeParameter", { fg = "#90abe5" })
hi(0, "CmpItemKindUnit", { fg = "#acce96" })
hi(0, "CmpItemKindValue", { fg = "#e8a380" })
hi(0, "CmpItemKindVariable", { fg = "#e8c1c1" })
hi(0, "CmpItemMenu", { fg = "#c8d0f0" })
hi(0, "ColorColumn", { bg = "#424556" })
hi(0, "Comment", { fg = "#777a86", italic = true })
hi(0, "Conceal", { fg = "#878c9a" })
hi(0, "Conditional", { fg = "#c6a2de", italic = true })
hi(0, "Constant", { fg = "#e8a380" })
hi(0, "CurSearch", { bg = "#e58385", fg = "#2c2d33" })
hi(0, "Cursor", { bg = "#c6d0f4", fg = "#33353b" })
hi(0, "CursorColumn", { bg = "#292c3a" })
hi(0, "CursorIM", { bg = "#c6d0f4", fg = "#33353b" })
hi(0, "CursorLine", { bg = "#3c3f50" })
hi(0, "CursorLineNr", { fg = "#bbbcea" })
hi(0, "DapBreakpoint", { fg = "#de8889" })
hi(0, "DapBreakpointCondition", { fg = "#e0c99d" })
hi(0, "DapBreakpointRejected", { fg = "#c6a2de" })
hi(0, "DapLogPoint", { fg = "#a5ced6" })
hi(0, "DapStopped", { fg = "#e29ea0" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#acce96" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#676970" })
hi(0, "DapUIBreakpointsInfo", { fg = "#acce96" })
hi(0, "DapUIBreakpointsPath", { fg = "#a5ced6" })
hi(0, "DapUIDecoration", { fg = "#a5ced6" })
hi(0, "DapUIFloatBorder", { fg = "#a5ced6" })
hi(0, "DapUILineNumber", { fg = "#a5ced6" })
hi(0, "DapUIModifiedValue", { fg = "#e8a380" })
hi(0, "DapUIPlayPause", { fg = "#acce96" })
hi(0, "DapUIRestart", { fg = "#acce96" })
hi(0, "DapUIScope", { fg = "#a5ced6" })
hi(0, "DapUISource", { fg = "#bbbcea" })
hi(0, "DapUIStepBack", { fg = "#90abe5" })
hi(0, "DapUIStepInto", { fg = "#90abe5" })
hi(0, "DapUIStepOut", { fg = "#90abe5" })
hi(0, "DapUIStepOver", { fg = "#90abe5" })
hi(0, "DapUIStop", { fg = "#de8889" })
hi(0, "DapUIStoppedThread", { fg = "#a5ced6" })
hi(0, "DapUIThread", { fg = "#acce96" })
hi(0, "DapUIType", { fg = "#c6a2de" })
hi(0, "DapUIUnavailable", { fg = "#57585c" })
hi(0, "DapUIValue", { fg = "#a5ced6" })
hi(0, "DapUIVariable", { fg = "#c8d0f0" })
hi(0, "DapUIWatchesEmpty", { fg = "#e29ea0" })
hi(0, "DapUIWatchesError", { fg = "#e29ea0" })
hi(0, "DapUIWatchesValue", { fg = "#acce96" })
hi(0, "DapUIWinSelect", { fg = "#e8a380" })
hi(0, "DashboardCenter", { fg = "#acce96" })
hi(0, "DashboardDesc", { fg = "#90abe5" })
hi(0, "DashboardFiles", { fg = "#bbbcea" })
hi(0, "DashboardFooter", { fg = "#e0c99d", italic = true })
hi(0, "DashboardHeader", { fg = "#90abe5" })
hi(0, "DashboardIcon", { bold = true, fg = "#eebce1" })
hi(0, "DashboardKey", { fg = "#e8a380" })
hi(0, "DashboardMruTitle", { fg = "#a5ced6" })
hi(0, "DashboardProjectTitle", { fg = "#a5ced6" })
hi(0, "DashboardShortCut", { fg = "#eebce1" })
hi(0, "Delimiter", { fg = "#979db0" })
hi(0, "DiagnosticError", { fg = "#de8889", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#de8889" })
hi(0, "DiagnosticFloatingHint", { fg = "#8dc5bd" })
hi(0, "DiagnosticFloatingInfo", { fg = "#a5ced6" })
hi(0, "DiagnosticFloatingWarn", { fg = "#e0c99d" })
hi(0, "DiagnosticHint", { fg = "#8dc5bd", italic = true })
hi(0, "DiagnosticInfo", { fg = "#a5ced6", italic = true })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#bcf3c6" })
hi(0, "DiagnosticSignError", { fg = "#de8889" })
hi(0, "DiagnosticSignHint", { fg = "#8dc5bd" })
hi(0, "DiagnosticSignInfo", { fg = "#a5ced6" })
hi(0, "DiagnosticSignWarn", { fg = "#e0c99d" })
hi(0, "DiagnosticUnderlineError", { sp = "#e78284", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#81c8be", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#99d1db", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e5c890", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#413b4a", fg = "#de8889", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#39424f", fg = "#8dc5bd", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#3b4352", fg = "#a5ced6", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#41424b", fg = "#e0c99d", italic = true })
hi(0, "DiagnosticWarn", { fg = "#e0c99d", italic = true })
hi(0, "DiffAdd", { bg = "#465052" })
hi(0, "DiffChange", { bg = "#373c50" })
hi(0, "DiffDelete", { bg = "#504350" })
hi(0, "DiffText", { bg = "#4d5775" })
hi(0, "Directory", { fg = "#90abe5" })
hi(0, "DropBarIconUISeparator", { fg = "#878c9a" })
hi(0, "DropBarKindArray", { fg = "#c8d0f0" })
hi(0, "DropBarKindBoolean", { fg = "#c8d0f0" })
hi(0, "DropBarKindBreakStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindCall", { fg = "#c8d0f0" })
hi(0, "DropBarKindCaseStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindClass", { fg = "#c8d0f0" })
hi(0, "DropBarKindConstant", { fg = "#c8d0f0" })
hi(0, "DropBarKindConstructor", { fg = "#c8d0f0" })
hi(0, "DropBarKindContinueStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindDeclaration", { fg = "#c8d0f0" })
hi(0, "DropBarKindDelete", { fg = "#c8d0f0" })
hi(0, "DropBarKindDoStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindElseStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindEnum", { fg = "#c8d0f0" })
hi(0, "DropBarKindEnumMember", { fg = "#c8d0f0" })
hi(0, "DropBarKindEvent", { fg = "#c8d0f0" })
hi(0, "DropBarKindField", { fg = "#c8d0f0" })
hi(0, "DropBarKindFile", { fg = "#c8d0f0" })
hi(0, "DropBarKindFolder", { fg = "#c8d0f0" })
hi(0, "DropBarKindForStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindFunction", { fg = "#c8d0f0" })
hi(0, "DropBarKindIdentifier", { fg = "#c8d0f0" })
hi(0, "DropBarKindIfStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindInterface", { fg = "#c8d0f0" })
hi(0, "DropBarKindKeyword", { fg = "#c8d0f0" })
hi(0, "DropBarKindList", { fg = "#c8d0f0" })
hi(0, "DropBarKindMacro", { fg = "#c8d0f0" })
hi(0, "DropBarKindMarkdownH1", { fg = "#c8d0f0" })
hi(0, "DropBarKindMarkdownH2", { fg = "#c8d0f0" })
hi(0, "DropBarKindMarkdownH3", { fg = "#c8d0f0" })
hi(0, "DropBarKindMarkdownH4", { fg = "#c8d0f0" })
hi(0, "DropBarKindMarkdownH5", { fg = "#c8d0f0" })
hi(0, "DropBarKindMarkdownH6", { fg = "#c8d0f0" })
hi(0, "DropBarKindMethod", { fg = "#c8d0f0" })
hi(0, "DropBarKindModule", { fg = "#c8d0f0" })
hi(0, "DropBarKindNamespace", { fg = "#c8d0f0" })
hi(0, "DropBarKindNull", { fg = "#c8d0f0" })
hi(0, "DropBarKindNumber", { fg = "#c8d0f0" })
hi(0, "DropBarKindObject", { fg = "#c8d0f0" })
hi(0, "DropBarKindOperator", { fg = "#c8d0f0" })
hi(0, "DropBarKindPackage", { fg = "#c8d0f0" })
hi(0, "DropBarKindProperty", { fg = "#c8d0f0" })
hi(0, "DropBarKindReference", { fg = "#c8d0f0" })
hi(0, "DropBarKindRepeat", { fg = "#c8d0f0" })
hi(0, "DropBarKindScope", { fg = "#c8d0f0" })
hi(0, "DropBarKindSpecifier", { fg = "#c8d0f0" })
hi(0, "DropBarKindStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindString", { fg = "#c8d0f0" })
hi(0, "DropBarKindStruct", { fg = "#c8d0f0" })
hi(0, "DropBarKindSwitchStatement", { fg = "#c8d0f0" })
hi(0, "DropBarKindType", { fg = "#c8d0f0" })
hi(0, "DropBarKindTypeParameter", { fg = "#c8d0f0" })
hi(0, "DropBarKindUnit", { fg = "#c8d0f0" })
hi(0, "DropBarKindValue", { fg = "#c8d0f0" })
hi(0, "DropBarKindVariable", { fg = "#c8d0f0" })
hi(0, "DropBarKindWhileStatement", { fg = "#c8d0f0" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#33353b" })
hi(0, "Error", { fg = "#de8889" })
hi(0, "ErrorMsg", { bold = true, fg = "#de8889", italic = true })
hi(0, "Exception", { fg = "#c6a2de" })
hi(0, "FlashBackdrop", { fg = "#777a86" })
hi(0, "FlashCurrent", { bg = "#313444", fg = "#e8a380" })
hi(0, "FlashLabel", { bg = "#313444", bold = true, fg = "#acce96" })
hi(0, "FlashMatch", { bg = "#313444", fg = "#bbbcea" })
hi(0, "FlashPrompt", { link = "NormalFloat" })
hi(0, "FloatBorder", { fg = "#90abe5" })
hi(0, "FloatShadow", { bg = "#515254", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#515254", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { fg = "#a8aec5" })
hi(0, "FoldColumn", { fg = "#777a86" })
hi(0, "Folded", { bg = "#52576a", fg = "#90abe5" })
hi(0, "Function", { fg = "#90abe5" })
hi(0, "GitSignsAdd", { fg = "#acce96" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#e0c99d" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#57585c" })
hi(0, "GitSignsDelete", { fg = "#de8889" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#56664b" })
hi(0, "GitSignsStagedAddLn", { bg = "#465052" })
hi(0, "GitSignsStagedAddNr", { fg = "#56664b" })
hi(0, "GitSignsStagedChange", { fg = "#6f654f" })
hi(0, "GitSignsStagedChangeLn", { bg = "#373c50" })
hi(0, "GitSignsStagedChangeNr", { fg = "#6f654f" })
hi(0, "GitSignsStagedChangedelete", { fg = "#6f654f" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#373c50" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#6f654f" })
hi(0, "GitSignsStagedDelete", { fg = "#6b4646" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#6b4646" })
hi(0, "GitSignsStagedTopdelete", { fg = "#6b4646" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#6b4646" })
hi(0, "GlyphPalette1", { fg = "#de8889" })
hi(0, "GlyphPalette2", { fg = "#8dc5bd" })
hi(0, "GlyphPalette3", { fg = "#e0c99d" })
hi(0, "GlyphPalette4", { fg = "#90abe5" })
hi(0, "GlyphPalette6", { fg = "#8dc5bd" })
hi(0, "GlyphPalette7", { fg = "#c8d0f0" })
hi(0, "GlyphPalette9", { fg = "#de8889" })
hi(0, "IblIndent", { fg = "#45464c" })
hi(0, "IblScope", { fg = "#c8d0f0" })
hi(0, "Identifier", { fg = "#e8c1c1" })
hi(0, "IlluminatedWordRead", { bg = "#484d5e" })
hi(0, "IlluminatedWordText", { bg = "#484d5e" })
hi(0, "IlluminatedWordWrite", { bg = "#484d5e" })
hi(0, "IncSearch", { bg = "#91c1cb", fg = "#2c2d33" })
hi(0, "Include", { fg = "#c6a2de" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#c6a2de" })
hi(0, "Label", { fg = "#90bfd5" })
hi(0, "LineNr", { fg = "#57585c" })
hi(0, "LspCodeLens", { fg = "#777a86" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#de8889" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#8dc5bd" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#a5ced6" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#e0c99d" })
hi(0, "LspDiagnosticsError", { fg = "#de8889" })
hi(0, "LspDiagnosticsHint", { fg = "#8dc5bd" })
hi(0, "LspDiagnosticsInformation", { fg = "#a5ced6" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#e78284", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#81c8be", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#99d1db", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#e5c890", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#de8889", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#8dc5bd", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#a5ced6", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#e0c99d", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#e0c99d" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#3c3f50", fg = "#777a86" })
hi(0, "LspReferenceRead", { bg = "#52576a" })
hi(0, "LspReferenceText", { bg = "#52576a" })
hi(0, "LspReferenceWrite", { bg = "#52576a" })
hi(0, "LspSignatureActiveParameter", { fg = "#e8a380" })
hi(0, "Macro", { fg = "#c6a2de" })
hi(0, "MatchParen", { bg = "#52576a", bold = true, fg = "#e8a380" })
hi(0, "ModeMsg", { bold = true, fg = "#c8d0f0" })
hi(0, "MoreMsg", { fg = "#90abe5" })
hi(0, "MsgSeparator", {})
hi(0, "NeogitBranch", { bold = true, fg = "#e8a380" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#acce96" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#e0c99d" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#eebce1" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#de8889" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#90abe5" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#acce96" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#e8a380" })
hi(0, "NeogitCommitViewHeader", { bg = "#4d5775", fg = "#9cb2e7" })
hi(0, "NeogitDiffAdd", { bg = "#3c434b", fg = "#94af87" })
hi(0, "NeogitDiffAddHighlight", { bg = "#5a6a5e", fg = "#b2cda6" })
hi(0, "NeogitDiffContext", { bg = "#313444" })
hi(0, "NeogitDiffContextHighlight", { bg = "#424556" })
hi(0, "NeogitDiffDelete", { bg = "#413b4a", fg = "#b6797d" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#6d505b", fg = "#d99499" })
hi(0, "NeogitDiffHeader", { bg = "#313444", bold = true, fg = "#90abe5" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#313444", bold = true, fg = "#e8a380" })
hi(0, "NeogitFilePath", { fg = "#90abe5", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#90abe5" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#90abe5" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#90abe5" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#b7bfdb" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#acce96" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#bbbcea" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#de8889" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#e0c99d" })
hi(0, "NeogitGraphCyan", { fg = "#90abe5" })
hi(0, "NeogitGraphGray", { fg = "#b7bfdb" })
hi(0, "NeogitGraphGreen", { fg = "#acce96" })
hi(0, "NeogitGraphOrange", { fg = "#e8a380" })
hi(0, "NeogitGraphPurple", { fg = "#bbbcea" })
hi(0, "NeogitGraphRed", { fg = "#de8889" })
hi(0, "NeogitGraphWhite", { fg = "#33353b" })
hi(0, "NeogitGraphYellow", { fg = "#e0c99d" })
hi(0, "NeogitHunkHeader", { bg = "#3a3f53", fg = "#65708b" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#454d67", fg = "#90abe5" })
hi(0, "NeogitNotificationError", { fg = "#de8889" })
hi(0, "NeogitNotificationInfo", { fg = "#90abe5" })
hi(0, "NeogitNotificationWarning", { fg = "#e0c99d" })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitPopupActionKey", { fg = "#bbbcea" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#bbbcea" })
hi(0, "NeogitPopupOptionKey", { fg = "#bbbcea" })
hi(0, "NeogitPopupSwitchKey", { fg = "#bbbcea" })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitRemote", { bold = true, fg = "#acce96" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitTagDistance", { fg = "#90abe5" })
hi(0, "NeogitTagName", { fg = "#e0c99d" })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#bbbcea" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#c6a2de" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#c6a2de" })
hi(0, "NonText", { fg = "#777a86" })
hi(0, "Normal", { bg = "#313444", fg = "#c8d0f0" })
hi(0, "NormalFloat", { bg = "#292c3a", fg = "#c8d0f0" })
hi(0, "NormalNC", { bg = "#313444", fg = "#c8d0f0" })
hi(0, "NormalSB", { bg = "#232632", fg = "#c8d0f0" })
hi(0, "Number", { fg = "#e8a380" })
hi(0, "NvimInternalError", { bg = "#fd120b", ctermbg = 9, ctermfg = 9, fg = "#f53023" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#90abe5" })
hi(0, "NvimTreeFolderIcon", { fg = "#90abe5" })
hi(0, "NvimTreeFolderName", { fg = "#90abe5" })
hi(0, "NvimTreeGitDeleted", { fg = "#de8889" })
hi(0, "NvimTreeGitDirty", { fg = "#e0c99d" })
hi(0, "NvimTreeGitNew", { fg = "#90abe5" })
hi(0, "NvimTreeImageFile", { fg = "#c8d0f0" })
hi(0, "NvimTreeIndentMarker", { fg = "#777a86" })
hi(0, "NvimTreeNormal", { bg = "#292c3a", fg = "#c8d0f0" })
hi(0, "NvimTreeOpenedFile", { fg = "#eebce1" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#90abe5" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#bbbcea" })
hi(0, "NvimTreeSpecialFile", { fg = "#e8c1c1" })
hi(0, "NvimTreeStatuslineNc", { bg = "#292c3a", fg = "#2c2d33" })
hi(0, "NvimTreeSymlink", { fg = "#eebce1" })
hi(0, "NvimTreeWinSeparator", { bg = "#313444", fg = "#33353b" })
hi(0, "Operator", { fg = "#a5ced6" })
hi(0, "Pmenu", { bg = "#3c3f50", fg = "#979db0" })
hi(0, "PmenuSbar", { bg = "#52576a" })
hi(0, "PmenuSel", { bg = "#52576a", bold = true })
hi(0, "PmenuThumb", { bg = "#747991" })
hi(0, "PreProc", { fg = "#eebce1" })
hi(0, "Question", { fg = "#90abe5" })
hi(0, "QuickFixLine", { bg = "#52576a", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#90abe5" })
hi(0, "RainbowDelimiterCyan", { fg = "#8dc5bd" })
hi(0, "RainbowDelimiterGreen", { fg = "#acce96" })
hi(0, "RainbowDelimiterOrange", { fg = "#e8a380" })
hi(0, "RainbowDelimiterRed", { fg = "#de8889" })
hi(0, "RainbowDelimiterViolet", { fg = "#c6a2de" })
hi(0, "RainbowDelimiterYellow", { fg = "#e0c99d" })
hi(0, "RedrawDebugClear", { bg = "#6b5304", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#045524", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#580209", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#fac2bc" })
hi(0, "Repeat", { fg = "#c6a2de" })
hi(0, "Search", { bg = "#516372", fg = "#c8d0f0" })
hi(0, "SignColumn", { fg = "#57585c" })
hi(0, "SignColumnSB", { bg = "#232632", fg = "#57585c" })
hi(0, "Special", { fg = "#eebce1" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#e78284", undercurl = true })
hi(0, "SpellCap", { sp = "#e5c890", undercurl = true })
hi(0, "SpellLocal", { sp = "#8caaee", undercurl = true })
hi(0, "SpellRare", { sp = "#a6d189", undercurl = true })
hi(0, "Statement", { fg = "#c6a2de" })
hi(0, "StatusLine", { bg = "#292c3a", fg = "#c8d0f0" })
hi(0, "StatusLineNC", { bg = "#292c3a", fg = "#57585c" })
hi(0, "StorageClass", { fg = "#e0c99d" })
hi(0, "String", { fg = "#acce96" })
hi(0, "Structure", { fg = "#e0c99d" })
hi(0, "Substitute", { bg = "#52576a", fg = "#eebce1" })
hi(0, "TabLine", { bg = "#292c3a", fg = "#57585c" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#52576a", fg = "#acce96" })
hi(0, "Tag", { bold = true, fg = "#bbbcea" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#90abe5" })
hi(0, "TelescopeSelection", { bg = "#424556", bold = true, fg = "#c8d0f0" })
hi(0, "TelescopeSelectionCaret", { fg = "#e8c1c1" })
hi(0, "Title", { bold = true, fg = "#90abe5" })
hi(0, "Todo", { bg = "#edbfbf", bold = true, fg = "#33353b" })
hi(0, "Type", { fg = "#e0c99d" })
hi(0, "UfoFoldedEllipsis", { bg = "#8daaec", fg = "#25272c" })
hi(0, "UfoFoldedFg", { fg = "#bbbcea" })
hi(0, "VertSplit", { fg = "#25272c" })
hi(0, "Visual", { bg = "#52576a", bold = true })
hi(0, "VisualNOS", { bg = "#52576a", bold = true })
hi(0, "WarningMsg", { fg = "#e0c99d" })
hi(0, "Whitespace", { fg = "#57585c" })
hi(0, "WildMenu", { bg = "#747991" })
hi(0, "WinBar", { fg = "#eed7d2" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#25272c" })
hi(0, "debugBreakpoint", { bg = "#313444", fg = "#777a86" })
hi(0, "debugPC", { bg = "#232632" })
hi(0, "diffAdded", { fg = "#acce96" })
hi(0, "diffChanged", { fg = "#90abe5" })
hi(0, "diffFile", { fg = "#90abe5" })
hi(0, "diffIndexLine", { fg = "#8dc5bd" })
hi(0, "diffLine", { fg = "#777a86" })
hi(0, "diffNewFile", { fg = "#e8a380" })
hi(0, "diffOldFile", { fg = "#e0c99d" })
hi(0, "diffRemoved", { fg = "#de8889" })
hi(0, "gitCommitSummary", { fg = "#eed7d2", italic = true })
hi(0, "healthError", { fg = "#de8889" })
hi(0, "healthSuccess", { fg = "#8dc5bd" })
hi(0, "healthWarning", { fg = "#e0c99d" })
hi(0, "htmlH1", { bold = true, fg = "#eebce1" })
hi(0, "htmlH2", { bold = true, fg = "#90abe5" })
hi(0, "illuminatedCurWord", { bg = "#52576a" })
hi(0, "illuminatedWord", { bg = "#52576a" })
hi(0, "lCursor", { bg = "#c6d0f4", fg = "#33353b" })
hi(0, "markdownCode", { fg = "#e8c1c1" })
hi(0, "markdownCodeBlock", { fg = "#e8c1c1" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#e8a380" })
hi(0, "markdownLinkText", { fg = "#90abe5", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#313444", fg = "#c8d0f0" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#e8c1c1" })
hi(0, "mkdCodeStart", { bold = true, fg = "#e8c1c1" })
hi(0, "qfFileName", { fg = "#90abe5" })
hi(0, "qfLineNr", { fg = "#e0c99d" })
hi(0, "rainbow1", { fg = "#de8889" })
hi(0, "rainbow2", { fg = "#e8a380" })
hi(0, "rainbow3", { fg = "#e0c99d" })
hi(0, "rainbow4", { fg = "#acce96" })
hi(0, "rainbow5", { fg = "#90bfd5" })
hi(0, "rainbow6", { fg = "#bbbcea" })
hi(0, "zshKSHFunction", { link = "Function" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1c1c1c"
g.terminal_color_1 = "#d75f5f"
g.terminal_color_2 = "#87af87"
g.terminal_color_3 = "#afaf87"
g.terminal_color_4 = "#5f87af"
g.terminal_color_5 = "#af87af"
g.terminal_color_6 = "#5f8787"
g.terminal_color_7 = "#9e9e9e"
g.terminal_color_8 = "#767676"
g.terminal_color_9 = "#d7875f"
g.terminal_color_10 = "#afd7af"
g.terminal_color_11 = "#d7d787"
g.terminal_color_12 = "#87afd7"
g.terminal_color_13 = "#d7afd7"
g.terminal_color_14 = "#87afaf"
g.terminal_color_15 = "#bcbcbc"
