-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then vim.cmd('highlight clear') end
vim.g.colors_name = "catppuccin-ivo"

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { link = "Constant" })
hi(0, "@character.special", { link = "SpecialChar" })
hi(0, "@comment.error", { bg = "#c08484", fg = "#4b4d53" })
hi(0, "@comment.hint", { bg = "#8a9dc9", fg = "#4b4d53" })
hi(0, "@comment.note", { bg = "#8a9dc9", fg = "#4b4d53" })
hi(0, "@comment.todo", { bg = "#cfb8b8", fg = "#4b4d53" })
hi(0, "@comment.warning", { bg = "#ccbca0", fg = "#4b4d53" })
hi(0, "@comment.warning.gitcommit", { fg = "#fde5b8" })
hi(0, "@conditional", { link = "Conditional" })
hi(0, "@constant.builtin", { fg = "#ffbe9b" })
hi(0, "@constant.java", { fg = "#a8e1d9" })
hi(0, "@constant.macro", { link = "Macro" })
hi(0, "@constructor", { fg = "#abdbf1" })
hi(0, "@constructor.lua", { fg = "#ffdddd" })
hi(0, "@constructor.tsx", { fg = "#d7d8ff" })
hi(0, "@constructor.typescript", { fg = "#d7d8ff" })
hi(0, "@define", { link = "Define" })
hi(0, "@diff.delta", { link = "diffChanged" })
hi(0, "@diff.minus", { link = "diffRemoved" })
hi(0, "@diff.plus", { link = "diffAdded" })
hi(0, "@error", { link = "Error" })
hi(0, "@exception", { link = "Exception" })
hi(0, "@field", { fg = "#d7d8ff" })
hi(0, "@float", { link = "Float" })
hi(0, "@function.builtin", { fg = "#ffbe9b" })
hi(0, "@function.builtin.bash", { fg = "#fca3a3", italic = true })
hi(0, "@function.call", { link = "Function" })
hi(0, "@function.macro", { fg = "#a8e1d9" })
hi(0, "@function.method", { link = "Function" })
hi(0, "@function.method.call", { link = "Function" })
hi(0, "@function.method.call.php", { link = "Function" })
hi(0, "@function.method.php", { link = "Function" })
hi(0, "@include", { link = "Include" })
hi(0, "@keyword.conditional", { link = "Conditional" })
hi(0, "@keyword.directive", { link = "PreProc" })
hi(0, "@keyword.directive.define", { link = "Define" })
hi(0, "@keyword.exception", { link = "Exception" })
hi(0, "@keyword.export", { fg = "#c0eaf2" })
hi(0, "@keyword.function", { fg = "#e2bdfb" })
hi(0, "@keyword.import", { link = "Include" })
hi(0, "@keyword.operator", { fg = "#e2bdfb" })
hi(0, "@keyword.repeat", { link = "Repeat" })
hi(0, "@keyword.return", { fg = "#e2bdfb" })
hi(0, "@keyword.storage", { link = "StorageClass" })
hi(0, "@label.json", { fg = "#abc7ff" })
hi(0, "@lsp.type.boolean", { link = "@boolean" })
hi(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hi(0, "@lsp.type.class", { link = "@type" })
hi(0, "@lsp.type.comment", { link = "@comment" })
hi(0, "@lsp.type.decorator", { link = "@attribute" })
hi(0, "@lsp.type.enum", { link = "@type" })
hi(0, "@lsp.type.enumMember", { link = "@constant" })
hi(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hi(0, "@lsp.type.event", { link = "@type" })
hi(0, "@lsp.type.formatSpecifier", { link = "@punctuation.special" })
hi(0, "@lsp.type.function", { link = "@function" })
hi(0, "@lsp.type.interface", { fg = "#ffdddd" })
hi(0, "@lsp.type.keyword", { link = "@keyword" })
hi(0, "@lsp.type.macro", { link = "@constant.macro" })
hi(0, "@lsp.type.method", { link = "@function.method" })
hi(0, "@lsp.type.modifier", { link = "@type.qualifier" })
hi(0, "@lsp.type.namespace", { link = "@namespace" })
hi(0, "@lsp.type.number", { link = "@number" })
hi(0, "@lsp.type.operator", { link = "@operator" })
hi(0, "@lsp.type.parameter", { link = "@parameter" })
hi(0, "@lsp.type.property", { link = "@property" })
hi(0, "@lsp.type.regexp", { link = "@string.regexp" })
hi(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hi(0, "@lsp.type.string", { link = "@string" })
hi(0, "@lsp.type.struct", { link = "@type" })
hi(0, "@lsp.type.type", { link = "@type" })
hi(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hi(0, "@lsp.type.typeParameter", { link = "@type.definition" })
hi(0, "@lsp.type.unresolvedReference", { link = "@error" })
hi(0, "@lsp.type.variable", {})
hi(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hi(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hi(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hi(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hi(0, "@lsp.typemod.string.injected", { link = "@string" })
hi(0, "@lsp.typemod.type.defaultLibrary", { link = "@type.builtin" })
hi(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hi(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hi(0, "@markup", { fg = "#e7edff" })
hi(0, "@markup.environment", { fg = "#ffdbfa" })
hi(0, "@markup.environment.name", { fg = "#abc7ff" })
hi(0, "@markup.heading", { bold = true, fg = "#abc7ff" })
hi(0, "@markup.heading.1.markdown", { link = "rainbow1" })
hi(0, "@markup.heading.2.markdown", { link = "rainbow2" })
hi(0, "@markup.heading.3.markdown", { link = "rainbow3" })
hi(0, "@markup.heading.4.markdown", { link = "rainbow4" })
hi(0, "@markup.heading.5.markdown", { link = "rainbow5" })
hi(0, "@markup.heading.6.markdown", { link = "rainbow6" })
hi(0, "@markup.italic", { fg = "#ffb9bb", italic = true })
hi(0, "@markup.link", { link = "Tag" })
hi(0, "@markup.link.url", { fg = "#fff7f4", italic = true, underline = true })
hi(0, "@markup.list", { link = "Special" })
hi(0, "@markup.list.checked", { fg = "#c7eab1" })
hi(0, "@markup.list.unchecked", { fg = "#a1a6b5" })
hi(0, "@markup.math", { fg = "#abc7ff" })
hi(0, "@markup.raw", { fg = "#a8e1d9" })
hi(0, "@markup.strikethrough", { fg = "#e7edff", strikethrough = true })
hi(0, "@markup.strong", { bold = true, fg = "#ffb9bb" })
hi(0, "@markup.underline", { link = "Underlined" })
hi(0, "@method", { link = "Function" })
hi(0, "@method.call", { link = "Function" })
hi(0, "@method.call.php", { link = "Function" })
hi(0, "@method.php", { link = "Function" })
hi(0, "@module", { fg = "#d7d8ff", italic = true })
hi(0, "@module.builtin", { link = "Special" })
hi(0, "@namespace", { fg = "#d7d8ff", italic = true })
hi(0, "@number.css", { fg = "#ffbe9b" })
hi(0, "@number.float", { link = "Float" })
hi(0, "@parameter", { fg = "#ffb9bb" })
hi(0, "@preproc", { link = "PreProc" })
hi(0, "@property", { fg = "#d7d8ff" })
hi(0, "@property.class.css", { fg = "#fde5b8" })
hi(0, "@property.cpp", { fg = "#e7edff" })
hi(0, "@property.css", { fg = "#d7d8ff" })
hi(0, "@property.id.css", { fg = "#abc7ff" })
hi(0, "@property.toml", { fg = "#abc7ff" })
hi(0, "@property.typescript", { fg = "#d7d8ff" })
hi(0, "@punctuation.bracket", { fg = "#b2b8cb" })
hi(0, "@punctuation.delimiter", { link = "Delimiter" })
hi(0, "@punctuation.special", { link = "Special" })
hi(0, "@repeat", { link = "Repeat" })
hi(0, "@storageclass", { link = "StorageClass" })
hi(0, "@string.escape", { fg = "#ffdbfa" })
hi(0, "@string.plain.css", { fg = "#ffbe9b" })
hi(0, "@string.regex", { fg = "#ffbe9b" })
hi(0, "@string.regexp", { fg = "#ffbe9b" })
hi(0, "@string.special", { link = "Special" })
hi(0, "@string.special.symbol", { fg = "#ffdddd" })
hi(0, "@string.special.symbol.ruby", { fg = "#ffdddd" })
hi(0, "@string.special.url", { fg = "#fff7f4", italic = true, underline = true })
hi(0, "@symbol", { fg = "#ffdddd" })
hi(0, "@symbol.ruby", { fg = "#ffdddd" })
hi(0, "@tag", { fg = "#e2bdfb" })
hi(0, "@tag.attribute", { fg = "#a8e1d9", italic = true })
hi(0, "@tag.attribute.tsx", { fg = "#a8e1d9", italic = true })
hi(0, "@tag.delimiter", { fg = "#c0eaf2" })
hi(0, "@text", { fg = "#e7edff" })
hi(0, "@text.danger", { bg = "#c08484", fg = "#4b4d53" })
hi(0, "@text.diff.add", { link = "diffAdded" })
hi(0, "@text.diff.delete", { link = "diffRemoved" })
hi(0, "@text.emphasis", { fg = "#ffb9bb", italic = true })
hi(0, "@text.environment", { fg = "#ffdbfa" })
hi(0, "@text.environment.name", { fg = "#abc7ff" })
hi(0, "@text.literal", { fg = "#a8e1d9" })
hi(0, "@text.math", { fg = "#abc7ff" })
hi(0, "@text.note", { bg = "#8a9dc9", fg = "#4b4d53" })
hi(0, "@text.reference", { link = "Tag" })
hi(0, "@text.strike", { fg = "#e7edff", strikethrough = true })
hi(0, "@text.strong", { bold = true, fg = "#ffb9bb" })
hi(0, "@text.title", { bold = true, fg = "#abc7ff" })
hi(0, "@text.title.1.markdown", { link = "rainbow1" })
hi(0, "@text.title.2.markdown", { link = "rainbow2" })
hi(0, "@text.title.3.markdown", { link = "rainbow3" })
hi(0, "@text.title.4.markdown", { link = "rainbow4" })
hi(0, "@text.title.5.markdown", { link = "rainbow5" })
hi(0, "@text.title.6.markdown", { link = "rainbow6" })
hi(0, "@text.todo", { bg = "#cfb8b8", fg = "#4b4d53" })
hi(0, "@text.todo.checked", { fg = "#c7eab1" })
hi(0, "@text.todo.unchecked", { fg = "#a1a6b5" })
hi(0, "@text.underline", { link = "Underlined" })
hi(0, "@text.warning", { bg = "#ccbca0", fg = "#4b4d53" })
hi(0, "@type.builtin", { fg = "#fde5b8" })
hi(0, "@type.builtin.c", { fg = "#fde5b8" })
hi(0, "@type.builtin.cpp", { fg = "#fde5b8" })
hi(0, "@type.css", { fg = "#d7d8ff" })
hi(0, "@type.definition", { link = "Type" })
hi(0, "@type.qualifier", { link = "Keyword" })
hi(0, "@type.tag.css", { fg = "#e2bdfb" })
hi(0, "@variable", { fg = "#e7edff" })
hi(0, "@variable.builtin", { fg = "#fca3a3" })
hi(0, "@variable.member", { fg = "#d7d8ff" })
hi(0, "@variable.parameter", { fg = "#ffb9bb" })
hi(0, "Added", { ctermfg = 10, fg = "#ffffff" })
hi(0, "AlphaButtons", { fg = "#d7d8ff" })
hi(0, "AlphaFooter", { fg = "#fde5b8", italic = true })
hi(0, "AlphaHeader", { fg = "#abc7ff" })
hi(0, "AlphaHeaderLabel", { fg = "#ffbe9b" })
hi(0, "AlphaShortcut", { fg = "#c7eab1" })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = "#ffbe9b" })
hi(0, "Changed", { ctermfg = 14, fg = "#feffff" })
hi(0, "Character", { fg = "#a8e1d9" })
hi(0, "CmpItemAbbr", { fg = "#b2b8cb" })
hi(0, "CmpItemAbbrDeprecated", { fg = "#9194a0", strikethrough = true })
hi(0, "CmpItemAbbrMatch", { bold = true, fg = "#e7edff" })
hi(0, "CmpItemAbbrMatchFuzzy", { bold = true, fg = "#e7edff" })
hi(0, "CmpItemKind", { fg = "#abc7ff" })
hi(0, "CmpItemKindClass", { fg = "#fde5b8" })
hi(0, "CmpItemKindColor", { fg = "#fca3a3" })
hi(0, "CmpItemKindConstant", { fg = "#ffbe9b" })
hi(0, "CmpItemKindConstructor", { fg = "#abc7ff" })
hi(0, "CmpItemKindCopilot", { fg = "#a8e1d9" })
hi(0, "CmpItemKindEnum", { fg = "#c7eab1" })
hi(0, "CmpItemKindEnumMember", { fg = "#fca3a3" })
hi(0, "CmpItemKindEvent", { fg = "#abc7ff" })
hi(0, "CmpItemKindField", { fg = "#c7eab1" })
hi(0, "CmpItemKindFile", { fg = "#abc7ff" })
hi(0, "CmpItemKindFolder", { fg = "#abc7ff" })
hi(0, "CmpItemKindFunction", { fg = "#abc7ff" })
hi(0, "CmpItemKindInterface", { fg = "#fde5b8" })
hi(0, "CmpItemKindKeyword", { fg = "#fca3a3" })
hi(0, "CmpItemKindMethod", { fg = "#abc7ff" })
hi(0, "CmpItemKindModule", { fg = "#abc7ff" })
hi(0, "CmpItemKindOperator", { fg = "#abc7ff" })
hi(0, "CmpItemKindProperty", { fg = "#c7eab1" })
hi(0, "CmpItemKindReference", { fg = "#fca3a3" })
hi(0, "CmpItemKindSnippet", { fg = "#e2bdfb" })
hi(0, "CmpItemKindStruct", { fg = "#abc7ff" })
hi(0, "CmpItemKindText", { fg = "#a8e1d9" })
hi(0, "CmpItemKindTypeParameter", { fg = "#abc7ff" })
hi(0, "CmpItemKindUnit", { fg = "#c7eab1" })
hi(0, "CmpItemKindValue", { fg = "#ffbe9b" })
hi(0, "CmpItemKindVariable", { fg = "#ffdddd" })
hi(0, "CmpItemMenu", { fg = "#e7edff" })
hi(0, "ColorColumn", { bg = "#3a3a3a" })
hi(0, "Comment", { fg = "#9194a0", italic = true })
hi(0, "Conceal", { fg = "#a1a6b5" })
hi(0, "Conditional", { fg = "#e2bdfb", italic = true })
hi(0, "Constant", { fg = "#ffbe9b" })
hi(0, "CurSearch", { bg = "#c08484", fg = "#43454b" })
hi(0, "Cursor", { bg = "#bcc3d8", fg = "#4b4d53" })
hi(0, "CursorColumn", { bg = "#212121" })
hi(0, "CursorIM", { bg = "#bcc3d8", fg = "#4b4d53" })
hi(0, "CursorLine", { bg = "#343434" })
hi(0, "CursorLineNr", { fg = "#d7d8ff" })
hi(0, "DapBreakpoint", { fg = "#fca3a3" })
hi(0, "DapBreakpointCondition", { fg = "#fde5b8" })
hi(0, "DapBreakpointRejected", { fg = "#e2bdfb" })
hi(0, "DapLogPoint", { fg = "#c0eaf2" })
hi(0, "DapStopped", { fg = "#ffb9bb" })
hi(0, "DapUIBreakpointsCurrentLine", { bold = true, fg = "#c7eab1" })
hi(0, "DapUIBreakpointsDisabledLine", { fg = "#80828a" })
hi(0, "DapUIBreakpointsInfo", { fg = "#c7eab1" })
hi(0, "DapUIBreakpointsPath", { fg = "#c0eaf2" })
hi(0, "DapUIDecoration", { fg = "#c0eaf2" })
hi(0, "DapUIFloatBorder", { fg = "#c0eaf2" })
hi(0, "DapUILineNumber", { fg = "#c0eaf2" })
hi(0, "DapUIModifiedValue", { fg = "#ffbe9b" })
hi(0, "DapUIPlayPause", { fg = "#c7eab1" })
hi(0, "DapUIRestart", { fg = "#c7eab1" })
hi(0, "DapUIScope", { fg = "#c0eaf2" })
hi(0, "DapUISource", { fg = "#d7d8ff" })
hi(0, "DapUIStepBack", { fg = "#abc7ff" })
hi(0, "DapUIStepInto", { fg = "#abc7ff" })
hi(0, "DapUIStepOut", { fg = "#abc7ff" })
hi(0, "DapUIStepOver", { fg = "#abc7ff" })
hi(0, "DapUIStop", { fg = "#fca3a3" })
hi(0, "DapUIStoppedThread", { fg = "#c0eaf2" })
hi(0, "DapUIThread", { fg = "#c7eab1" })
hi(0, "DapUIType", { fg = "#e2bdfb" })
hi(0, "DapUIUnavailable", { fg = "#707175" })
hi(0, "DapUIValue", { fg = "#c0eaf2" })
hi(0, "DapUIVariable", { fg = "#e7edff" })
hi(0, "DapUIWatchesEmpty", { fg = "#ffb9bb" })
hi(0, "DapUIWatchesError", { fg = "#ffb9bb" })
hi(0, "DapUIWatchesValue", { fg = "#c7eab1" })
hi(0, "DapUIWinSelect", { fg = "#ffbe9b" })
hi(0, "DashboardCenter", { fg = "#c7eab1" })
hi(0, "DashboardDesc", { fg = "#abc7ff" })
hi(0, "DashboardFiles", { fg = "#d7d8ff" })
hi(0, "DashboardFooter", { fg = "#fde5b8", italic = true })
hi(0, "DashboardHeader", { fg = "#abc7ff" })
hi(0, "DashboardIcon", { bold = true, fg = "#ffdbfa" })
hi(0, "DashboardKey", { fg = "#ffbe9b" })
hi(0, "DashboardMruTitle", { fg = "#c0eaf2" })
hi(0, "DashboardProjectTitle", { fg = "#c0eaf2" })
hi(0, "DashboardShortCut", { fg = "#ffdbfa" })
hi(0, "Delimiter", { fg = "#b2b8cb" })
hi(0, "DiagnosticError", { fg = "#fca3a3", italic = true })
hi(0, "DiagnosticFloatingError", { fg = "#fca3a3" })
hi(0, "DiagnosticFloatingHint", { fg = "#a8e1d9" })
hi(0, "DiagnosticFloatingInfo", { fg = "#c0eaf2" })
hi(0, "DiagnosticFloatingWarn", { fg = "#fde5b8" })
hi(0, "DiagnosticHint", { fg = "#a8e1d9", italic = true })
hi(0, "DiagnosticInfo", { fg = "#c0eaf2", italic = true })
hi(0, "DiagnosticOk", { ctermfg = 10, fg = "#ffffff" })
hi(0, "DiagnosticSignError", { fg = "#fca3a3" })
hi(0, "DiagnosticSignHint", { fg = "#a8e1d9" })
hi(0, "DiagnosticSignInfo", { fg = "#c0eaf2" })
hi(0, "DiagnosticSignWarn", { fg = "#fde5b8" })
hi(0, "DiagnosticUnderlineError", { sp = "#e78284", underline = true })
hi(0, "DiagnosticUnderlineHint", { sp = "#81c8be", underline = true })
hi(0, "DiagnosticUnderlineInfo", { sp = "#99d1db", underline = true })
hi(0, "DiagnosticUnderlineWarn", { sp = "#e5c890", underline = true })
hi(0, "DiagnosticVirtualTextError", { bg = "#323232", fg = "#fca3a3", italic = true })
hi(0, "DiagnosticVirtualTextHint", { bg = "#353536", fg = "#a8e1d9", italic = true })
hi(0, "DiagnosticVirtualTextInfo", { bg = "#373737", fg = "#c0eaf2", italic = true })
hi(0, "DiagnosticVirtualTextWarn", { bg = "#373737", fg = "#fde5b8", italic = true })
hi(0, "DiagnosticWarn", { fg = "#fde5b8", italic = true })
hi(0, "DiagnosticUnnecessary", { link = "DiagnosticUnderlineWarn" })
hi(0, "DiffAdd", { bg = "#424242" })
hi(0, "DiffChange", { bg = "#313131" })
hi(0, "DiffDelete", { bg = "#3c3c3c" })
hi(0, "DiffText", { bg = "#4c4c4c" })
hi(0, "Directory", { fg = "#abc7ff" })
hi(0, "DropBarIconUISeparator", { fg = "#a1a6b5" })
hi(0, "DropBarKindArray", { fg = "#e7edff" })
hi(0, "DropBarKindBoolean", { fg = "#e7edff" })
hi(0, "DropBarKindBreakStatement", { fg = "#e7edff" })
hi(0, "DropBarKindCall", { fg = "#e7edff" })
hi(0, "DropBarKindCaseStatement", { fg = "#e7edff" })
hi(0, "DropBarKindClass", { fg = "#e7edff" })
hi(0, "DropBarKindConstant", { fg = "#e7edff" })
hi(0, "DropBarKindConstructor", { fg = "#e7edff" })
hi(0, "DropBarKindContinueStatement", { fg = "#e7edff" })
hi(0, "DropBarKindDeclaration", { fg = "#e7edff" })
hi(0, "DropBarKindDelete", { fg = "#e7edff" })
hi(0, "DropBarKindDoStatement", { fg = "#e7edff" })
hi(0, "DropBarKindElseStatement", { fg = "#e7edff" })
hi(0, "DropBarKindEnum", { fg = "#e7edff" })
hi(0, "DropBarKindEnumMember", { fg = "#e7edff" })
hi(0, "DropBarKindEvent", { fg = "#e7edff" })
hi(0, "DropBarKindField", { fg = "#e7edff" })
hi(0, "DropBarKindFile", { fg = "#e7edff" })
hi(0, "DropBarKindFolder", { fg = "#e7edff" })
hi(0, "DropBarKindForStatement", { fg = "#e7edff" })
hi(0, "DropBarKindFunction", { fg = "#e7edff" })
hi(0, "DropBarKindIdentifier", { fg = "#e7edff" })
hi(0, "DropBarKindIfStatement", { fg = "#e7edff" })
hi(0, "DropBarKindInterface", { fg = "#e7edff" })
hi(0, "DropBarKindKeyword", { fg = "#e7edff" })
hi(0, "DropBarKindList", { fg = "#e7edff" })
hi(0, "DropBarKindMacro", { fg = "#e7edff" })
hi(0, "DropBarKindMarkdownH1", { fg = "#e7edff" })
hi(0, "DropBarKindMarkdownH2", { fg = "#e7edff" })
hi(0, "DropBarKindMarkdownH3", { fg = "#e7edff" })
hi(0, "DropBarKindMarkdownH4", { fg = "#e7edff" })
hi(0, "DropBarKindMarkdownH5", { fg = "#e7edff" })
hi(0, "DropBarKindMarkdownH6", { fg = "#e7edff" })
hi(0, "DropBarKindMethod", { fg = "#e7edff" })
hi(0, "DropBarKindModule", { fg = "#e7edff" })
hi(0, "DropBarKindNamespace", { fg = "#e7edff" })
hi(0, "DropBarKindNull", { fg = "#e7edff" })
hi(0, "DropBarKindNumber", { fg = "#e7edff" })
hi(0, "DropBarKindObject", { fg = "#e7edff" })
hi(0, "DropBarKindOperator", { fg = "#e7edff" })
hi(0, "DropBarKindPackage", { fg = "#e7edff" })
hi(0, "DropBarKindProperty", { fg = "#e7edff" })
hi(0, "DropBarKindReference", { fg = "#e7edff" })
hi(0, "DropBarKindRepeat", { fg = "#e7edff" })
hi(0, "DropBarKindScope", { fg = "#e7edff" })
hi(0, "DropBarKindSpecifier", { fg = "#e7edff" })
hi(0, "DropBarKindStatement", { fg = "#e7edff" })
hi(0, "DropBarKindString", { fg = "#e7edff" })
hi(0, "DropBarKindStruct", { fg = "#e7edff" })
hi(0, "DropBarKindSwitchStatement", { fg = "#e7edff" })
hi(0, "DropBarKindType", { fg = "#e7edff" })
hi(0, "DropBarKindTypeParameter", { fg = "#e7edff" })
hi(0, "DropBarKindUnit", { fg = "#e7edff" })
hi(0, "DropBarKindValue", { fg = "#e7edff" })
hi(0, "DropBarKindVariable", { fg = "#e7edff" })
hi(0, "DropBarKindWhileStatement", { fg = "#e7edff" })
hi(0, "DropBarMenuHoverEntry", { link = "Visual" })
hi(0, "DropBarMenuHoverIcon", { reverse = true })
hi(0, "DropBarMenuHoverSymbol", { bold = true })
hi(0, "EndOfBuffer", { fg = "#4b4d53" })
hi(0, "Error", { fg = "#fca3a3" })
hi(0, "ErrorMsg", { bold = true, fg = "#fca3a3", italic = true })
hi(0, "Exception", { fg = "#e2bdfb" })
hi(0, "FlashBackdrop", { fg = "#9194a0" })
hi(0, "FlashCurrent", { bg = "#292929", fg = "#ffbe9b" })
hi(0, "FlashLabel", { bg = "#292929", bold = true, fg = "#c7eab1" })
hi(0, "FlashMatch", { bg = "#292929", fg = "#d7d8ff" })
hi(0, "FlashPrompt", { link = "NormalFloat" })
hi(0, "FloatBorder", { fg = "#abc7ff" })
hi(0, "FloatShadow", { bg = "#464646", blend = 80, ctermbg = 0 })
hi(0, "FloatShadowThrough", { bg = "#464646", blend = 100, ctermbg = 0 })
hi(0, "FloatTitle", { fg = "#c3c9e1" })
hi(0, "FoldColumn", { fg = "#9194a0" })
hi(0, "Folded", { bg = "#4c4c4c", fg = "#abc7ff" })
hi(0, "Function", { fg = "#abc7ff" })
hi(0, "FzfLuaBufFlagAlt", { fg = "#ffffff" })
hi(0, "FzfLuaBufFlagCur", { fg = "#ff7a70" })
hi(0, "FzfLuaBufLineNr", { fg = "#c2ffd9" })
hi(0, "FzfLuaBufName", { fg = "#ffeaff" })
hi(0, "FzfLuaBufNr", { fg = "#ffffff" })
hi(0, "FzfLuaHeaderBind", { fg = "#ffffff" })
hi(0, "FzfLuaHeaderText", { fg = "#ff7a70" })
hi(0, "FzfLuaLiveSym", { fg = "#ff7a70" })
hi(0, "FzfLuaTabMarker", { bold = true, fg = "#ffffff" })
hi(0, "FzfLuaTabTitle", { bold = true, fg = "#ecf8ff" })
hi(0, "GitSignsAdd", { fg = "#c7eab1" })
hi(0, "GitSignsAddPreview", { link = "DiffAdd" })
hi(0, "GitSignsChange", { fg = "#fde5b8" })
hi(0, "GitSignsCurrentLineBlame", { fg = "#707175" })
hi(0, "GitSignsDelete", { fg = "#fca3a3" })
hi(0, "GitSignsDeletePreview", { link = "DiffDelete" })
hi(0, "GitSignsStagedAdd", { fg = "#6f7f63" })
hi(0, "GitSignsStagedAddLn", { bg = "#424242" })
hi(0, "GitSignsStagedAddNr", { fg = "#6f7f63" })
hi(0, "GitSignsStagedChange", { fg = "#897e68" })
hi(0, "GitSignsStagedChangeLn", { bg = "#313131" })
hi(0, "GitSignsStagedChangeNr", { fg = "#897e68" })
hi(0, "GitSignsStagedChangedelete", { fg = "#897e68" })
hi(0, "GitSignsStagedChangedeleteLn", { bg = "#313131" })
hi(0, "GitSignsStagedChangedeleteNr", { fg = "#897e68" })
hi(0, "GitSignsStagedDelete", { fg = "#855e5e" })
hi(0, "GitSignsStagedDeleteNr", { fg = "#855e5e" })
hi(0, "GitSignsStagedTopdelete", { fg = "#855e5e" })
hi(0, "GitSignsStagedTopdeleteNr", { fg = "#855e5e" })
hi(0, "GlyphPalette1", { fg = "#fca3a3" })
hi(0, "GlyphPalette2", { fg = "#a8e1d9" })
hi(0, "GlyphPalette3", { fg = "#fde5b8" })
hi(0, "GlyphPalette4", { fg = "#abc7ff" })
hi(0, "GlyphPalette6", { fg = "#a8e1d9" })
hi(0, "GlyphPalette7", { fg = "#e7edff" })
hi(0, "GlyphPalette9", { fg = "#fca3a3" })
hi(0, "IblIndent", { fg = "#5d5e65" })
hi(0, "IblScope", { fg = "#e7edff" })
hi(0, "Identifier", { fg = "#ffdddd" })
hi(0, "IlluminatedWordRead", { bg = "#424242" })
hi(0, "IlluminatedWordText", { bg = "#424242" })
hi(0, "IlluminatedWordWrite", { bg = "#424242" })
hi(0, "IncSearch", { bg = "#98afb3", fg = "#43454b" })
hi(0, "Include", { fg = "#e2bdfb" })
hi(0, "Italic", { italic = true })
hi(0, "Keyword", { fg = "#e2bdfb" })
hi(0, "Label", { fg = "#abdbf1" })
hi(0, "LineNr", { fg = "#707175" })
hi(0, "LspCodeLens", { fg = "#9194a0" })
hi(0, "LspDiagnosticsDefaultError", { fg = "#fca3a3" })
hi(0, "LspDiagnosticsDefaultHint", { fg = "#a8e1d9" })
hi(0, "LspDiagnosticsDefaultInformation", { fg = "#c0eaf2" })
hi(0, "LspDiagnosticsDefaultWarning", { fg = "#fde5b8" })
hi(0, "LspDiagnosticsError", { fg = "#fca3a3" })
hi(0, "LspDiagnosticsHint", { fg = "#a8e1d9" })
hi(0, "LspDiagnosticsInformation", { fg = "#c0eaf2" })
hi(0, "LspDiagnosticsUnderlineError", { sp = "#e78284", underline = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = "#81c8be", underline = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = "#99d1db", underline = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = "#e5c890", underline = true })
hi(0, "LspDiagnosticsVirtualTextError", { fg = "#fca3a3", italic = true })
hi(0, "LspDiagnosticsVirtualTextHint", { fg = "#a8e1d9", italic = true })
hi(0, "LspDiagnosticsVirtualTextInformation", { fg = "#c0eaf2", italic = true })
hi(0, "LspDiagnosticsVirtualTextWarning", { fg = "#fde5b8", italic = true })
hi(0, "LspDiagnosticsWarning", { fg = "#fde5b8" })
hi(0, "LspInfoBorder", { link = "FloatBorder" })
hi(0, "LspInlayHint", { bg = "#343434", fg = "#9194a0" })
hi(0, "LspReferenceRead", { bg = "#4c4c4c" })
hi(0, "LspReferenceText", { bg = "#4c4c4c" })
hi(0, "LspReferenceWrite", { bg = "#4c4c4c" })
hi(0, "LspSignatureActiveParameter", {bold = true, underline = true})
hi(0, "Macro", { fg = "#e2bdfb" })
hi(0, "MatchParen", { bg = "#4c4c4c", bold = true, fg = "#ffbe9b" })
hi(0, "ModeMsg", { bold = true, fg = "#e7edff" })
hi(0, "MoreMsg", { fg = "#abc7ff" })
hi(0, "MsgSeparator", {})
hi(0, "NeogitBranch", { bold = true, fg = "#ffbe9b" })
hi(0, "NeogitChangeAdded", { bold = true, fg = "#c7eab1" })
hi(0, "NeogitChangeBothModified", { bold = true, fg = "#fde5b8" })
hi(0, "NeogitChangeCopied", { bold = true, fg = "#ffdbfa" })
hi(0, "NeogitChangeDeleted", { bold = true, fg = "#fca3a3" })
hi(0, "NeogitChangeModified", { bold = true, fg = "#abc7ff" })
hi(0, "NeogitChangeNewFile", { bold = true, fg = "#c7eab1" })
hi(0, "NeogitChangeRenamed", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitChangeUpdated", { bold = true, fg = "#ffbe9b" })
hi(0, "NeogitCommitViewHeader", { bg = "#4c4c4c", fg = "#b7ceff" })
hi(0, "NeogitDiffAdd", { bg = "#363636", fg = "#afcaa1" })
hi(0, "NeogitDiffAddHighlight", { bg = "#585a58", fg = "#cde9c1" })
hi(0, "NeogitDiffContext", { bg = "#292929" })
hi(0, "NeogitDiffContextHighlight", { bg = "#3a3a3a" })
hi(0, "NeogitDiffDelete", { bg = "#323232", fg = "#d29397" })
hi(0, "NeogitDiffDeleteHighlight", { bg = "#514c4e", fg = "#f6afb4" })
hi(0, "NeogitDiffHeader", { bg = "#292929", bold = true, fg = "#abc7ff" })
hi(0, "NeogitDiffHeaderHighlight", { bg = "#292929", bold = true, fg = "#ffbe9b" })
hi(0, "NeogitFilePath", { fg = "#abc7ff", italic = true })
hi(0, "NeogitGraphBlue", { fg = "#abc7ff" })
hi(0, "NeogitGraphBoldBlue", { bold = true, fg = "#abc7ff" })
hi(0, "NeogitGraphBoldCyan", { bold = true, fg = "#abc7ff" })
hi(0, "NeogitGraphBoldGray", { bold = true, fg = "#d3dbf8" })
hi(0, "NeogitGraphBoldGreen", { bold = true, fg = "#c7eab1" })
hi(0, "NeogitGraphBoldPurple", { bold = true, fg = "#d7d8ff" })
hi(0, "NeogitGraphBoldRed", { bold = true, fg = "#fca3a3" })
hi(0, "NeogitGraphBoldWhite", { bold = true })
hi(0, "NeogitGraphBoldYellow", { bold = true, fg = "#fde5b8" })
hi(0, "NeogitGraphCyan", { fg = "#abc7ff" })
hi(0, "NeogitGraphGray", { fg = "#d3dbf8" })
hi(0, "NeogitGraphGreen", { fg = "#c7eab1" })
hi(0, "NeogitGraphOrange", { fg = "#ffbe9b" })
hi(0, "NeogitGraphPurple", { fg = "#d7d8ff" })
hi(0, "NeogitGraphRed", { fg = "#fca3a3" })
hi(0, "NeogitGraphWhite", { fg = "#4b4d53" })
hi(0, "NeogitGraphYellow", { fg = "#fde5b8" })
hi(0, "NeogitHunkHeader", { bg = "#343434", fg = "#7e8aa6" })
hi(0, "NeogitHunkHeaderHighlight", { bg = "#424242", fg = "#abc7ff" })
hi(0, "NeogitNotificationError", { fg = "#fca3a3" })
hi(0, "NeogitNotificationInfo", { fg = "#abc7ff" })
hi(0, "NeogitNotificationWarning", { fg = "#fde5b8" })
hi(0, "NeogitObjectId", { link = "Comment" })
hi(0, "NeogitPopupActionKey", { fg = "#d7d8ff" })
hi(0, "NeogitPopupBold", { bold = true })
hi(0, "NeogitPopupConfigKey", { fg = "#d7d8ff" })
hi(0, "NeogitPopupOptionKey", { fg = "#d7d8ff" })
hi(0, "NeogitPopupSwitchKey", { fg = "#d7d8ff" })
hi(0, "NeogitRebaseDone", { link = "Comment" })
hi(0, "NeogitRebasing", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitRecentcommits", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitRemote", { bold = true, fg = "#c7eab1" })
hi(0, "NeogitSectionHeader", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitStagedchanges", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitStash", { link = "Comment" })
hi(0, "NeogitStashes", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitTagDistance", { fg = "#abc7ff" })
hi(0, "NeogitTagName", { fg = "#fde5b8" })
hi(0, "NeogitUnmergedInto", { link = "Function" })
hi(0, "NeogitUnmergedchanges", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitUnpulledFrom", { link = "Function" })
hi(0, "NeogitUnpulledchanges", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitUnpushedTo", { bold = true, fg = "#d7d8ff" })
hi(0, "NeogitUnstagedchanges", { bold = true, fg = "#e2bdfb" })
hi(0, "NeogitUntrackedfiles", { bold = true, fg = "#e2bdfb" })
hi(0, "NonText", { fg = "#9194a0" })
hi(0, "Normal", { bg = "#292929", fg = "#e7edff" })
hi(0, "NormalFloat", { bg = "#212121", fg = "#e7edff" })
hi(0, "NormalNC", { bg = "#292929", fg = "#e7edff" })
hi(0, "NormalSB", { bg = "#1b1b1b", fg = "#e7edff" })
hi(0, "Number", { fg = "#ffbe9b" })
hi(0, "NvimInternalError", { bg = "#d63d2f", ctermbg = 9, ctermfg = 9, fg = "#ff6754" })
hi(0, "NvimTreeEmptyFolderName", { fg = "#abc7ff" })
hi(0, "NvimTreeFolderIcon", { fg = "#abc7ff" })
hi(0, "NvimTreeFolderName", { fg = "#abc7ff" })
hi(0, "NvimTreeGitDeleted", { fg = "#fca3a3" })
hi(0, "NvimTreeGitDirty", { fg = "#fde5b8" })
hi(0, "NvimTreeGitNew", { fg = "#abc7ff" })
hi(0, "NvimTreeImageFile", { fg = "#e7edff" })
hi(0, "NvimTreeIndentMarker", { fg = "#9194a0" })
hi(0, "NvimTreeNormal", { bg = "#212121", fg = "#e7edff" })
hi(0, "NvimTreeOpenedFile", { fg = "#ffdbfa" })
hi(0, "NvimTreeOpenedFolderName", { fg = "#abc7ff" })
hi(0, "NvimTreeRootFolder", { bold = true, fg = "#d7d8ff" })
hi(0, "NvimTreeSpecialFile", { fg = "#ffdddd" })
hi(0, "NvimTreeStatuslineNc", { bg = "#212121", fg = "#43454b" })
hi(0, "NvimTreeSymlink", { fg = "#ffdbfa" })
hi(0, "NvimTreeWinSeparator", { bg = "#292929", fg = "#4b4d53" })
hi(0, "Operator", { fg = "#c0eaf2" })
hi(0, "Pmenu", { bg = "#343434", fg = "#b2b8cb" })
hi(0, "PmenuSbar", { bg = "#4c4c4c" })
hi(0, "PmenuSel", { bg = "#4c4c4c", bold = true })
hi(0, "PmenuThumb", { bg = "#6d6d6d" })
hi(0, "PreProc", { fg = "#ffdbfa" })
hi(0, "Question", { fg = "#abc7ff" })
hi(0, "QuickFixLine", { bg = "#4c4c4c", bold = true })
hi(0, "RainbowDelimiterBlue", { fg = "#abc7ff" })
hi(0, "RainbowDelimiterCyan", { fg = "#a8e1d9" })
hi(0, "RainbowDelimiterGreen", { fg = "#c7eab1" })
hi(0, "RainbowDelimiterOrange", { fg = "#ffbe9b" })
hi(0, "RainbowDelimiterRed", { fg = "#fca3a3" })
hi(0, "RainbowDelimiterViolet", { fg = "#e2bdfb" })
hi(0, "RainbowDelimiterYellow", { fg = "#fde5b8" })
hi(0, "RedrawDebugClear", { bg = "#59481a", ctermbg = 11, ctermfg = 0 })
hi(0, "RedrawDebugComposed", { bg = "#164522", ctermbg = 10, ctermfg = 0 })
hi(0, "RedrawDebugRecompose", { bg = "#3e0b0b", ctermbg = 9, ctermfg = 0 })
hi(0, "Removed", { ctermfg = 9, fg = "#ffe5e2" })
hi(0, "Repeat", { fg = "#e2bdfb" })
hi(0, "Search", { bg = "#4f555a", fg = "#e7edff" })
hi(0, "SignColumn", { fg = "#707175" })
hi(0, "SignColumnSB", { bg = "#1b1b1b", fg = "#707175" })
hi(0, "Special", { fg = "#ffdbfa" })
hi(0, "SpecialKey", { link = "NonText" })
hi(0, "SpellBad", { sp = "#e78284", undercurl = true })
hi(0, "SpellCap", { sp = "#e5c890", undercurl = true })
hi(0, "SpellLocal", { sp = "#8caaee", undercurl = true })
hi(0, "SpellRare", { sp = "#a6d189", undercurl = true })
hi(0, "Statement", { fg = "#e2bdfb" })
hi(0, "StatusLine", { bg = "#212121", fg = "#e7edff" })
hi(0, "StatusLineNC", { bg = "#212121", fg = "#707175" })
hi(0, "StorageClass", { fg = "#fde5b8" })
hi(0, "String", { fg = "#c7eab1" })
hi(0, "Structure", { fg = "#fde5b8" })
hi(0, "Substitute", { bg = "#4c4c4c", fg = "#ffdbfa" })
hi(0, "TabLine", { bg = "#212121", fg = "#707175" })
hi(0, "TabLineFill", {})
hi(0, "TabLineSel", { bg = "#4c4c4c", fg = "#c7eab1" })
hi(0, "Tag", { bold = true, fg = "#d7d8ff" })
hi(0, "TelescopeBorder", { link = "FloatBorder" })
hi(0, "TelescopeMatching", { fg = "#abc7ff" })
hi(0, "TelescopeSelection", { bg = "#3a3a3a", bold = true, fg = "#e7edff" })
hi(0, "TelescopeSelectionCaret", { fg = "#ffdddd" })
hi(0, "Title", { bold = true, fg = "#abc7ff" })
hi(0, "Todo", { bg = "#cfb8b8", bold = true, fg = "#4b4d53" })
hi(0, "Type", { fg = "#fde5b8" })
hi(0, "UfoFoldedEllipsis", { bg = "#8a9dc9", fg = "#3c3e44" })
hi(0, "UfoFoldedFg", { fg = "#d7d8ff" })
hi(0, "VertSplit", { fg = "#3c3e44" })
hi(0, "Visual", { bg = "#4c4c4c", bold = true })
hi(0, "VisualNOS", { bg = "#4c4c4c", bold = true })
hi(0, "WarningMsg", { fg = "#fde5b8" })
hi(0, "Whitespace", { fg = "#707175" })
hi(0, "WildMenu", { bg = "#6d6d6d" })
hi(0, "WinBar", { fg = "#fff7f4" })
hi(0, "WinBarNC", { link = "WinBar" })
hi(0, "WinSeparator", { fg = "#3c3e44" })
hi(0, "debugBreakpoint", { bg = "#292929", fg = "#9194a0" })
hi(0, "debugPC", { bg = "#1b1b1b" })
hi(0, "diffAdded", { fg = "#c7eab1" })
hi(0, "diffChanged", { fg = "#abc7ff" })
hi(0, "diffFile", { fg = "#abc7ff" })
hi(0, "diffIndexLine", { fg = "#a8e1d9" })
hi(0, "diffLine", { fg = "#9194a0" })
hi(0, "diffNewFile", { fg = "#ffbe9b" })
hi(0, "diffOldFile", { fg = "#fde5b8" })
hi(0, "diffRemoved", { fg = "#fca3a3" })
hi(0, "gitCommitSummary", { fg = "#fff7f4", italic = true })
hi(0, "healthError", { fg = "#fca3a3" })
hi(0, "healthSuccess", { fg = "#a8e1d9" })
hi(0, "healthWarning", { fg = "#fde5b8" })
hi(0, "htmlH1", { bold = true, fg = "#ffdbfa" })
hi(0, "htmlH2", { bold = true, fg = "#abc7ff" })
hi(0, "illuminatedCurWord", { bg = "#4c4c4c" })
hi(0, "illuminatedWord", { bg = "#4c4c4c" })
hi(0, "lCursor", { bg = "#bcc3d8", fg = "#4b4d53" })
hi(0, "markdownCode", { fg = "#ffdddd" })
hi(0, "markdownCodeBlock", { fg = "#ffdddd" })
hi(0, "markdownH1", { link = "rainbow1" })
hi(0, "markdownH2", { link = "rainbow2" })
hi(0, "markdownH3", { link = "rainbow3" })
hi(0, "markdownH4", { link = "rainbow4" })
hi(0, "markdownH5", { link = "rainbow5" })
hi(0, "markdownH6", { link = "rainbow6" })
hi(0, "markdownHeadingDelimiter", { bold = true, fg = "#ffbe9b" })
hi(0, "markdownLinkText", { fg = "#abc7ff", underline = true })
hi(0, "mkdCodeDelimiter", { bg = "#292929", fg = "#e7edff" })
hi(0, "mkdCodeEnd", { bold = true, fg = "#ffdddd" })
hi(0, "mkdCodeStart", { bold = true, fg = "#ffdddd" })
hi(0, "qfFileName", { fg = "#abc7ff" })
hi(0, "qfLineNr", { fg = "#fde5b8" })
hi(0, "rainbow1", { fg = "#fca3a3" })
hi(0, "rainbow2", { fg = "#ffbe9b" })
hi(0, "rainbow3", { fg = "#fde5b8" })
hi(0, "rainbow4", { fg = "#c7eab1" })
hi(0, "rainbow5", { fg = "#abdbf1" })
hi(0, "rainbow6", { fg = "#d7d8ff" })
hi(0, "zshKSHFunction", { link = "Function" })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = "#1c1c1c"
g.terminal_color_1 = "#d75f5f"
g.terminal_color_2 = "#87af87"
g.terminal_color_3 = "#afaf87"
g.terminal_color_4 = "#5f87af"
g.terminal_color_5 = "#af87af"
g.terminal_color_6 = "#5f8787"
g.terminal_color_7 = "#9e9e9e"
g.terminal_color_8 = "#767676"
g.terminal_color_9 = "#d7875f"
g.terminal_color_10 = "#afd7af"
g.terminal_color_11 = "#d7d787"
g.terminal_color_12 = "#87afd7"
g.terminal_color_13 = "#d7afd7"
g.terminal_color_14 = "#87afaf"
g.terminal_color_15 = "#bcbcbc"
