theme = "zed_onedark"
[keys.insert.j]
k = ["normal_mode"]

[editor]
line-number = "relative"
cursorline = true
bufferline = "never"
indent-guides.render = true
# indent-guides.skip-levels=1
completion-timeout = 5
color-modes = false

[editor.lsp]
display-inlay-hints = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
newline = "all"
tab = "all"
space = "all"
nbsp = "all"

[editor.whitespace.characters]
space = "·"
# nbsp = "⍽"
# nnbsp = "␣"
tab = "→"
newline = ""
# tabpad = "→" # Tabs will look like "→···" (depending on tab width)

[keys.normal.space]
"," = ":config-open"
"q" = ":buffer-close"
# Muscle memory
[keys.normal]
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"

# Make j and k behave as they do Vim when soft-wrap is enabled
j = "move_line_down"
k = "move_line_up"

[keys.select]
# Muscle memory
"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
u = "switch_to_lowercase"
U = "switch_to_uppercase"

# Visual-mode specific muscle memory
i = "select_textobject_inner"
a = "select_textobject_around"

# Make selecting lines in visual mode behave sensibly
k = ["extend_line_up", "extend_to_line_bounds"]
j = ["extend_line_down", "extend_to_line_bounds"]
