theme = "kanagawa"
[keys.insert.j]
k = "normal_mode" # Maps `jk` to exit insert mode

[editor]
line-number = "relative"
cursorline = true
bufferline = "always"
indent-guides.render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = false

[editor.statusline]
left = ["mode", "version-control", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = ""
